---
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: bridge
      namespace: keptn
    spec:
      selector:
        matchLabels:
          run: bridge
      replicas: 1
      template:
        metadata:
          labels:
            run: bridge
        spec:
          containers:
          - name: bridge
            image: keptn/bridge:feature.1276.20200124.0959
            ports:
            - containerPort: 3000
            resources:
              requests:
                memory: "64Mi"
                cpu: "50m"
              limits:
                memory: "128Mi"
                cpu: "500m"